# Generated by Django 6.0.1 on 2026-01-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('business_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('stall_location', models.CharField(max_length=500)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('total_credits', models.IntegerField(default=0)),
                ('hygiene_rating', models.CharField(blank=True, max_length=5)),
                ('certificate_issued_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
